[package]
name = "houseflow-device-virtual"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lighthouse-proto = { path = "../../lighthouse/proto" }
env_logger = "0.8"
log = "0.4"
bytes = "1.0"
tokio = { version = "1.4", features = ["full"] }
tokio-util = { version = "0.6", features = [ "codec" ] }
